---
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/intvschar
    username: postgres
    password: 198725
  jpa:
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create